name: Apply Templates and Create PR

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Target repository'
        required: true
        example: 'ballerina-platform/module-ballerinax-github'
      module_name:
        description: 'Module name of the connector'
        required: true
        example: 'github'
      ballerina_version:
        description: 'Ballerina version to be used for the connector'
        required: true
        example: '2201.9.0'
      module_version:
        description: 'Connector version'
        required: true
        default: '0.1.0'
        example: '1.0.0'
      target_branch:
        description: 'Target branch'
        required: false
        default: 'main'

jobs:
  apply_templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout template repository
        uses: actions/checkout@v3
        with:
          path: template-repo

      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.target_repo }}
          path: target-repo
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Ballerina
        uses: ballerina-platform/setup-ballerina@v1
        with:
          version: 2201.9.0

      - name: Apply templates and replace placeholders
        run: |
          
          cp -r template-repo/generated-connector-template/* target-repo/
          cd template-repo
          bal run scripts/replace_placeholders.bal -- ../target-repo/ ${{ github.event.inputs.module_name }} ${{ github.event.inputs.target_repo }} ${{ github.event.inputs.module_version }} ${{ github.event.inputs.ballerina_version }}
          cd ../target-repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b apply-templates-${{ github.run_number }}
          git add .
          git commit -m "Apply connector template"
          git push origin apply-templates-${{ github.run_number }}

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh pr create \
            --repo ${{ github.event.inputs.target_repo }} \
            --base ${{ github.event.inputs.target_branch }} \
            --head apply-templates-${{ github.run_number }} \
            --title "Apply templates from repo A with placeholders replaced" \
            --body "This PR applies templates from repo A to this repository, with placeholders replaced."