name: Create Connector Repository

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Name part of the new connector repository. Example: slack, discord, twitter'
        required: true
      module_name:
        description: 'Name of the module, only if it is different from the repository name.'
        required: false

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Template
        uses: actions/checkout@v2

      - name: Create Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repo_name="${{ github.event.inputs.repo_name }}"
          org="your-github-org"
          template_repo="ballerina-connector-template"
          
          # Create a new repository from the template
          curl -u "${{ secrets.GITHUB_TOKEN }}:x-oauth-basic" \
            https://api.github.com/repos/${org}/${template_repo}/generate \
            -d "{\"owner\":\"${org}\", \"name\":\"${repo_name}\", \"include_all_branches\":false, \"private\":false}"

          # Clone the newly created repository
          git clone https://github.com/${org}/${repo_name}.git
          cd ${repo_name}

          # Replace placeholders with the actual repository name
          find . -type f -exec sed -i "s/{{CONNECTOR_NAME}}/${repo_name}/g" {} \;

          # Commit the changes to a new branch
          git checkout -b initialize-repo
          git add .
          git commit -m "Initialize repository with connector name"

          # Push the branch to the new repository
          git push origin initialize-repo

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          repo_name="${{ github.event.inputs.repo_name }}"
          org="your-github-org"
          
          # Create a pull request from the new branch
          curl -u "${{ secrets.GITHUB_TOKEN }}:x-oauth-basic" \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${org}/${repo_name}/pulls \
            -d "{\"title\":\"Initialize repository with connector name\", \"head\":\"initialize-repo\", \"base\":\"main\", \"body\":\"This pull request initializes the repository with the connector name.\"}"
