name: Apply Templates and Create PR

on:
  workflow_dispatch:
    inputs:
      target_repo:
        description: 'Target repository (owner/repo)'
        required: true
      target_branch:
        description: 'Target branch'
        required: true
        default: 'main'

jobs:
  apply_templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo A
        uses: actions/checkout@v3
        with:
          path: lib-repo

      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.target_repo }}
          path: target-repo
          token: ${{ secrets.PAT_TOKEN }}

      - name: Apply templates
        run: |
          cp -r lib-repo/generated-connector-template/* target-repo/
          cd target-repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b apply-templates-${{ github.run_number }}
          git add .
          git commit -m "Apply templates from library repo"
          git push origin apply-templates-${{ github.run_number }}

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh pr create \
            --repo ${{ github.event.inputs.target_repo }} \
            --base ${{ github.event.inputs.target_branch }} \
            --head apply-templates-${{ github.run_number }} \
            --title "Apply templates from repo A" \
            --body "This PR applies templates from repo A to this repository."
